all: egipto5.jpeg chaco1984.jpg chaco2022.jpg genocidio_patagonia.jpg africa.png scienceAndCivilizationChina2.jpg mapaMundial.jpg chatGPT.jpeg tasamnia.jpg tonga_barco.jpg polynesia.png terrazas_arroz_c.jpg mapa_icosaedro_blanco.png madre-chimpance.jpg agua.jpg atomo_de_oxigeno.png cerebros.jpg cerebros_red.jpg Metodos2.png BP.png modelosGraficos.jpeg peligro_predador.jpeg fuego.jpg antartic.jpeg tsimane.jpg treeOfLife-liviano.png reciprocidad.jpeg regalo.png dedo.png cerradura.png deforestacion.jpg pachacuteckoricancha.jpg sidewalk_bubblegum_1997_4.png moneda-euro-liviana.png galton-board.jpg Elo1980.jpg boole.png sum_product.png test_chagas.png lifeHistory.jpeg biomassBarOn.png plata-potosi.jpg ttt_history.png python.png julia.png R.png cara-emoji.png cloroplastos.jpg fotosintesis.jpg hormigas2.jpg tsimane2.jpg messi_datos.jpeg

egipto5.jpeg:
	wget https://raw.githubusercontent.com/glandfried/images/master/egipto1.jpeg
	wget https://raw.githubusercontent.com/glandfried/images/master/egipto2.jpeg
	wget https://raw.githubusercontent.com/glandfried/images/master/egipto3.jpeg
	wget https://raw.githubusercontent.com/glandfried/images/master/egipto4.jpeg
	wget https://raw.githubusercontent.com/glandfried/images/master/egipto5.jpeg

chaco1984.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/chaco1984.jpg

chaco2022.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/chaco2022.jpg

genocidio_patagonia.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/genocidio_patagonia.jpg

africa.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/africa.png

scienceAndCivilizationChina2.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/scienceAndCivilizationChina2.jpg

mapaMundial.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/mapaMundial.jpg


chatGPT.jpeg:
	wget https://raw.githubusercontent.com/glandfried/images/master/chatGPT.jpeg

tasmania.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/tasmania.jpg

tonga_barco.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/tonga_barco.jpg
polynesia.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/polynesia.png

terrazas_arroz_c.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/terrazas_arroz_c.jpg -O terrazas_arroz_c.jpg

mapa_icosaedro_blanco.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/mapa_icosaedro_blanco.png -O mapa_icosaedro_blanco.png

madre-chimpance.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/madre-chimpance.jpg -O madre-chimpance.jpg

cerebros_red.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/cerebros_red.jpg -O cerebros_red.jpg


cerebros.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/cerebros.jpg -O cerebros.jpg

agua.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/agua.jpg -O agua.jpg


atomo_de_oxigeno.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/atomo_de_oxigeno.png -O atomo_de_oxigeno.png

messi_datos.jpeg:
	wget https://raw.githubusercontent.com/glandfried/images/master/messi_datos.jpeg -O messi_datos.jpeg

BP.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/logos/BP.png -O BP.png

Metodos2.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/logos/Metodos2.png -O Metodos2.png


deforestacion.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/deforestacion.jpg

modelosGraficos.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/modelosGraficos.jpeg

peligro_predador.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/peligro_predador.jpeg

fuego.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/fuego.jpg

antartic.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/antartic.jpeg

tsimane.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/tsimane.jpg

treeOfLife-liviano.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/treeOfLife-liviano.png

reciprocidad.jpeg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/reciprocidad.jpeg

regalo.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/regalo.png

dedo.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/dedo.png

cerradura.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/cerradura.png

pachacuteckoricancha.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/pachacuteckoricancha.jpg

inti.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/inti.png

sidewalk_bubblegum_1997_4.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sidewalk_bubblegum_1997_1.png
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sidewalk_bubblegum_1997_2.png
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sidewalk_bubblegum_1997_4.png

moneda-euro-liviana.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/moneda-euro-liviana.png

galton-board.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/galton-board.jpg

Elo1980.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/Elo1980.jpg

boole.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/boole.png

sum_product.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/sum_product.png

test_chagas.png:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/test_chagas.png

lifeHistory.jpeg:
	wget https://raw.githubusercontent.com/glandfried/images/master/lifeHistory.jpeg

biomassBarOn.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/biomassBarOn.png

plata-potosi.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/plata-potosi.jpg

ttt_history.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/ttt_history.png

R.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/R.png

julia.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/julia.png

python.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/python.png

cara-emoji.png:
	wget https://raw.githubusercontent.com/glandfried/images/master/cara-emoji.png

cloroplastos.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/cloroplastos.jpg

fotosintesis.jpg:
	wget https://raw.githubusercontent.com/glandfried/images/master/fotosintesis.jpg

hormigas2.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/hormigas2.jpg

tsimane2.jpg:
	wget https://raw.githubusercontent.com/BayesDeLasProvinciasUnidasDelSur/static/master/tsimane2.jpg

